// Generates dist/flow_action_script.js: the classifier + rules inlined,
// ready to paste into a Flow Designer "Script" step. Run: npm run build
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const config = fs.readFileSync(path.join(root, 'config', 'categories.json'), 'utf8');
let classifier = fs.readFileSync(path.join(root, 'src', 'classifier.js'), 'utf8');
classifier = classifier.replace(/if \(typeof module[\s\S]*$/, '').trim();

const out = `// AUTO-GENERATED by scripts/build.js. Do not edit; change config/categories.json.
// Flow Designer > Action/Script step. Inputs: incident_sys_id (String)
(function execute(inputs, outputs) {
  var CONFIG = ${config.trim()};

  ${classifier.replace(/\n/g, '\n  ')}

  var gr = new GlideRecord('incident');
  if (!gr.get(inputs.incident_sys_id)) {
    outputs.rule = 'not_found';
    return;
  }

  var result = classifyIncident(gr.getValue('short_description'), gr.getValue('description'), CONFIG);

  gr.setValue('category', result.category);
  if (result.subcategory) gr.setValue('subcategory', result.subcategory);
  gr.setValue('urgency', result.urgency);
  gr.setValue('impact', result.impact);

  var grp = new GlideRecord('sys_user_group');
  if (grp.get('name', result.assignment_group)) {
    gr.setValue('assignment_group', grp.getUniqueValue());
  }
  if (result.needs_review) {
    gr.work_notes = 'Auto-classification found no match. Please review manually.';
  } else {
    gr.work_notes = 'Auto-classified as "' + result.rule + '" (score ' + result.score + ').';
  }
  gr.update();

  outputs.rule = result.rule;
  outputs.assignment_group = result.assignment_group;
  outputs.needs_review = result.needs_review;
})(inputs, outputs);
`;

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.writeFileSync(path.join(root, 'dist', 'flow_action_script.js'), out);
console.log('Wrote dist/flow_action_script.js');
